# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ItalyInspireCadastreDownloader
                                 A QGIS plugin
 QGIS plugin for downloading cadastral data of cadastrals parcels and cadastral zoning in Italy.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-12
        copyright            : (C) 2025 by Geoinnova SL / Patricio Soriano & Miquel Febrer
        email                : correo@geoinnova.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ItalyInspireCadastreDownloader class from file ItalyInspireCadastreDownloader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Italy_Inspire_Cadastre_Downloader import ItalyInspireCadastreDownloader
    return ItalyInspireCadastreDownloader(iface)
